### ISSUE TITLE
Office hours

### ISSUE THREAD

**Issue by suprenant** [18F/agile#75]
What we're after:
 - Deepen communities of practice

From #wg-dataservices:
_for our regular working group meeting today, I think I’d like to try conducting as an office hours, where folks can bring up questions or issues they want to discuss. I know that several other working groups hold their regular meetings this way so I thought we’d give it a try. Drop in at 3:00 PM EDT if you want to raise a question or chat about a data topic._

Notes from 10/19 guild meeting:
 - Considering doing these close to where the work is happening, help people with their work
 - Help people in focused way – "I have this issue, looking for help"
 - How will people know it’s agile-related? Give a problem-oriented framing.

## Todos

* [ ] Ryan to draft language
* [ ] Ryan Send out invite on Dec 12

**Comment by afomi** [comment]
I currently have bandwidth to run this. Happy to pair 🖇 with somebody on Office Hours.

A 60 minute block every week or every-other-week?

**Comment by porta-antiporta** [comment]
@afomi that's awesome!  I think every other week as a start would be good.  Perhaps we ping the #g-agile channel for who would also have some time to pair?

**Comment by afomi** [comment]
@UchMok, @AlanAtlas, @abrouilette have also raised hands.  🙌 

Next steps:

* [ ] Coordinate a list of Office Hours Hosts. Who hosts when.
* [ ] Communicate Office Hours out audiences/attendees.

**Comment by suprenant** [comment]
@afomi checking in on office hours. Still interested in helping with this? Anything you'd need to help move things along?

**Comment by suprenant** [comment]
@afomi I added you to the TTS Guild Meetings & Office Hours calendar. Want to move the 12/7 event there so other folks are able to easily find it?

**Comment by afomi** [comment]
yes. will do soon, when greenlit. 👍

**Comment by afomi** [comment]
update: first office hours will be Friday, Dec 21. We expect it to be light, first run-through.

**Comment by suprenant** [comment]
As an update, we're looking at 3/1 for our first office hours session. We will focus this on TTS for now and have asked Jacqueline to check with Dominic/legal on anything we may be able to do outside of TTS and GSA.

**Comment by suprenant** [comment]
Ryan and I chatted with Angela Colter about offering office hours outside of TTS. This is something she's working on for the guilds, and we'll check back in in about a month. Until then, we will focus on providing office hours to TTS.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
